version: '3'

services:
    php-backend:
        container_name: my-php-backend
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: php-backend-image
        volumes:
            - "D:/workspace/php-plus-react-app:/var/www/html"
        ports: 
            - "8888:80"